### ISSUE TITLE
Runnable source code?

### ISSUE THREAD

**Issue by t-neumann** [pughlab/bamgineer#12]
Hi,

is there any runnable version of `bamgineer` to be found?

The one that is hosted here clearly cannot work, since e.g. it does not even process the input bam files from the arguments parser and several called methods e.g. `params.GetInputBam()` have never been defined anywhere.

**Comment by suluxan** [comment]
Please see [Running example Bamgineer workflow with Docker] in the README. Bamgineer can be run now with one "docker run" command for ease-of-use.
