### ISSUE TITLE
Param "--configFile"

### ISSUE THREAD

**Issue by sfbrunner** [pughlab/bamgineer#4]
Hi there,
I came across your CNV simulation algorithm in bioRxiv. I'm realising I might be an early adopter, but the tool seems to do exactly what I'm looking for, so I wanted to give it a try.
Trying to use it, I noticed the required parameter "-c/--configFile". I can guess what it does (specifying paths to common tools such as samtools), however, I could not find an example of an actual config file compatible with your code. Could you perhaps provide me with an example that I can adapt to my environment?

Thanks and best wishes
Simon

**Comment by soroushsamadian** [comment]
Hi Simon,

Thank you for your interest in the tool and apologies for the delay. I have provided a config file in the "/src" directory :

https://github.com/pughlab/bamgineer/blob/master/src/config_default.cfg

and as you correctly guessed it specifies the path to the tool's and files used by Bamginer. Please let me know if you have any other questions.

Best,

Soroush

**Comment by sfbrunner** [comment]
Hi Soroush,
Thanks for your response and apologies for my slow reply.
I tested using the config file. Unfortunately I do not have the two files defined as "vcf_path" and "exons_path". I thought those two files were optional and can be generated by bamgineer on-the-fly. However, when I do not set them in the config file, I get an error. Any advice?

Thanks!
Simon

**Comment by soroushsamadian** [comment]
Hi Simon,

In fact those are two mandatory inputs, that you need to have generated a priori. The file "exon_path" is a bed file of your target region and (doesn't need to be any version of reference whole exome sequencing; perhaps "target region" is a better name). It is a tab delimited file with three mandatory fields ("chr", "start", "stop" )and the vcf_path is the path to your heterozygous SNPs (e.g. generated by HaplotypeCaller, Varscan2, etc). Please let me know if it solves your problem. 

Thank you,
Soroush
