### ISSUE TITLE
Error in running run_example1.sh

### ISSUE THREAD

**Issue by vipuljain222** [pughlab/bamgineer#9]
Hi,
I am getting error while running run_example1.sh using example data set. I have recreated exons.bed as explained in input_preparation.md file and modified config file with appropriate path.

File structure:

|-- inputs
| |-- cnv.bed
| |-- config.cfg
| |-- config_ORI.cfg
| |-- exons.bed
| |-- exons_ORI.bed
| |-- normal_het.vcf
| -- normal_het.vcf.gz |-- outputs | |-- cnv_dir | |-- gain.bed
| |-- finalbams
| |-- haplotypedir
| | |-- bedtool.log
| | |-- chr21_exons_in_roigain.bed
| | |-- chr21_het_snpgain.bed
| | |-- exons_in_roigain.bed
| | -- het_snpgain.bed | |-- logs | |-- debug.log
| |-- phasedvcfdir
| | |-- hap1_het_filtered.bed
| | |-- hap1_het_filtered.log
| | |-- hap1_het_filtered.recode.vcf
| | |-- hap1_het.vcf
| | |-- hap2_het_filtered.bed
| | |-- hap2_het_filtered.log
| | |-- hap2_het_filtered.recode.vcf
| | |-- hap2_het.vcf
| | |-- normal_het_phased.log
| | |-- normal_het_phased.vcf.gz
| | |-- normal_het_phased.warnings
| | -- PHASED.BED |-- tmpbams
|-- scripts
| |-- beagle.log
| -- run_example1.sh |-- splitbams | |-- chr21.bam | |-- chr21.bam.bai | |-- chr21.byname.bam | |-- chr22.bam | |-- chr22.bam.bai |-- chr22.byname.bam

Here is the output:

/opt/installers/bamgineer/examples/outputs
___ phasing vcf file ___
beagle.09Nov15.d2a.jar
Copyright (C) 2014-2015 Brian L. Browning
Enter "java -jar beagle.jar" for a summary of command line arguments.
Start time: 01:04 PM IST on 25 Apr 2018

Command line: java -Xmx3641m -jar beagle.jar
gt=/opt/installers/bamgineer/examples/inputs/normal_het.vcf.gz
out=/opt/installers/bamgineer/examples/outputs/phasedvcfdir/normal_het_phased

No genetic map is specified: using 1 cM = 1 Mb

reference samples: 0
target samples: 1

Window 1 [ chr21:9414112-48119669 ]
target markers: 10225

Starting burn-in iterations

Window=1 Iteration=1
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

Window=1 Iteration=2
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

Window=1 Iteration=3
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

Window=1 Iteration=4
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

Window=1 Iteration=5
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

Window=1 Iteration=6
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

Window=1 Iteration=7
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

Window=1 Iteration=8
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

Window=1 Iteration=9
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

Window=1 Iteration=10
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

Starting phasing iterations

Window=1 Iteration=11
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

states/marker: 1.0

Window=1 Iteration=12
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

states/marker: 1.0

Window=1 Iteration=13
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

states/marker: 1.0

Window=1 Iteration=14
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

states/marker: 1.0

Window=1 Iteration=15
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 2.000 mean count/edge: 1

states/marker: 1.0

Window 2 [ chr22:16066867-51239065 ]
target markers: 3455

Starting burn-in iterations

Window=2 Iteration=1
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

Window=2 Iteration=2
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

Window=2 Iteration=3
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

Window=2 Iteration=4
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

Window=2 Iteration=5
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

Window=2 Iteration=6
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

Window=2 Iteration=7
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

Window=2 Iteration=8
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

Window=2 Iteration=9
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

Window=2 Iteration=10
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

Starting phasing iterations

Window=2 Iteration=11
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

states/marker: 1.0

Window=2 Iteration=12
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

states/marker: 1.0

Window=2 Iteration=13
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

states/marker: 1.0

Window=2 Iteration=14
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

states/marker: 1.0

Window=2 Iteration=15
Time for building model: 0 seconds
Time for sampling (singles): 0 seconds
DAG statistics
mean edges/level: 2 max edges/level: 2
mean edges/node: 1.999 mean count/edge: 1

states/marker: 1.0

Number of markers: 13680
Total time for building model: 1 second
Total time for sampling: 1 second
Total run time: 2 seconds

End time: 01:04 PM IST on 25 Apr 2018
beagle.09Nov15.d2a.jar finished

VCFtools - v0.1.12a
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
--vcf /opt/installers/bamgineer/examples/outputs/phasedvcfdir/hap1_het.vcf
--thin 50
--out /opt/installers/bamgineer/examples/outputs/phasedvcfdir/hap1_het_filtered
--recode

After filtering, kept 0 out of 0 Individuals
Outputting VCF file...
After filtering, kept 5324 out of a possible 6773 Sites
Run Time = 0.00 seconds

VCFtools - v0.1.12a
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
--vcf /opt/installers/bamgineer/examples/outputs/phasedvcfdir/hap2_het.vcf
--thin 50
--out /opt/installers/bamgineer/examples/outputs/phasedvcfdir/hap2_het_filtered
--recode

After filtering, kept 0 out of 0 Individuals
Outputting VCF file...
After filtering, kept 5424 out of a possible 6905 Sites
Run Time = 0.00 seconds
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from "/opt/installers/bamgineer/examples/outputs/tmpbams/chr21_r
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/installers/bamgineer/src/helpers/handlers.py", line 76, in receive
record = self.queue.get(True, self.polltime)
File "/usr/lib/python2.7/multiprocessing/queues.py", line 135, in get
res = self._recv()
TypeError: ('init() takes exactly 2 arguments (1 given)', <class 'pysam.utils.SamtoolsError'>, ())

**Comment by soroushsamadian** [comment]
Hi just to double check, do you provide "splitbams" directory where the input.bam is split by individual chromosome(also sorted by name) or do you let Bamgineer do it for you?

**Comment by vipuljain222** [comment]
Yes I have provided "splitbams" folder with chromosome wise bam files (chr21 and chr22)  downloaded from provided link and modified as explained in input_preparation.md file. 

Please see attached folder structure.

**Comment by vipuljain222** [comment]
Yes I have provided "splitbams" folder with chromosome wise bam files (chr21 and chr22) downloaded from provided link and modified as explained in input_preparation.md file.

Please see attached folder structure.
![bamgineer_folder_structure](https://user-images.githubusercontent.com/37868408/39393958-1327ccda-4ae9-11e8-84a9-3a8c8de9f949.png)

**Comment by vipuljain222** [comment]
Below are the logs when run with in-house bam without "splitbams" folder.

beagle.09Nov15.d2a.jar
Copyright (C) 2014-2015 Brian L. Browning
Enter "java -jar beagle.jar" for a summary of command line arguments.
Start time: 01:05 PM IST on 04 May 2018

Command line: java -Xmx3641m -jar beagle.jar
  gt=/opt/installers/bamgineer/CEPH_CCP_test_data/Newvar.vcf.gz
  out=/opt/installers/bamgineer/CEPH_CCP_test_data/CCP_SIMULATION040518_R1/phasedvcfdir/Newvar_phased

No genetic map is specified: using 1 cM = 1 Mb

reference samples:       0
target samples:          1

Window 1 [ chr1:2494330-2494330 ]
target markers:          1

Starting burn-in iterations

Window=1 Iteration=1
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

Window=1 Iteration=2
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

Window=1 Iteration=3
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

Window=1 Iteration=4
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

Window=1 Iteration=5
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

Window=1 Iteration=6
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

Window=1 Iteration=7
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

Window=1 Iteration=8
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

Window=1 Iteration=9
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

Window=1 Iteration=10
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

Starting phasing iterations

Window=1 Iteration=11
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

states/marker:    0.0

Window=1 Iteration=12
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

states/marker:    0.0

Window=1 Iteration=13
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

states/marker:    0.0

Window=1 Iteration=14
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

states/marker:    0.0

Window=1 Iteration=15
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  0.667  mean count/edge: 1

states/marker:    0.0

Window 2 [ chr2:30143499-42396722 ]
target markers:          2

Starting burn-in iterations

Window=2 Iteration=1
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

Window=2 Iteration=2
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

Window=2 Iteration=3
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

Window=2 Iteration=4
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

Window=2 Iteration=5
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

Window=2 Iteration=6
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

Window=2 Iteration=7
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

Window=2 Iteration=8
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

Window=2 Iteration=9
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

Window=2 Iteration=10
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

Starting phasing iterations

Window=2 Iteration=11
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

states/marker:    1.0

Window=2 Iteration=12
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

states/marker:    1.0

Window=2 Iteration=13
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

states/marker:    1.0

Window=2 Iteration=14
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

states/marker:    1.0

Window=2 Iteration=15
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.000  mean count/edge: 1

states/marker:    1.0

Window 3 [ chr6:32191730-51491884 ]
target markers:          8

Starting burn-in iterations

Window=3 Iteration=1
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.600  mean count/edge: 1

Window=3 Iteration=2
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 4
mean edges/node:  1.636  mean count/edge: 1

Window=3 Iteration=3
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 4
mean edges/node:  1.636  mean count/edge: 1

Window=3 Iteration=4
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 4
mean edges/node:  1.636  mean count/edge: 1

Window=3 Iteration=5
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 4
mean edges/node:  1.636  mean count/edge: 1

Window=3 Iteration=6
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 4
mean edges/node:  1.636  mean count/edge: 1

Window=3 Iteration=7
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 4
mean edges/node:  1.636  mean count/edge: 1

Window=3 Iteration=8
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 4
mean edges/node:  1.636  mean count/edge: 1

Window=3 Iteration=9
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 4
mean edges/node:  1.636  mean count/edge: 1

Window=3 Iteration=10
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 4
mean edges/node:  1.636  mean count/edge: 1

Starting phasing iterations

Window=3 Iteration=11
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.600  mean count/edge: 1

states/marker:    1.0

Window=3 Iteration=12
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.600  mean count/edge: 1

states/marker:    1.0

Window=3 Iteration=13
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.600  mean count/edge: 1

states/marker:    1.0

Window=3 Iteration=14
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.600  mean count/edge: 1

states/marker:    1.0

Window=3 Iteration=15
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.600  mean count/edge: 1

states/marker:    1.0

Window 4 [ chr8:30924557-30973957 ]
target markers:          3

Starting burn-in iterations

Window=4 Iteration=1
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.200  mean count/edge: 1

Window=4 Iteration=2
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 3      max edges/level: 4
mean edges/node:  1.000  mean count/edge: 1

Window=4 Iteration=3
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.200  mean count/edge: 1

Window=4 Iteration=4
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 3      max edges/level: 4
mean edges/node:  1.000  mean count/edge: 1

Window=4 Iteration=5
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.200  mean count/edge: 1

Window=4 Iteration=6
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 3      max edges/level: 4
mean edges/node:  1.000  mean count/edge: 1

Window=4 Iteration=7
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.200  mean count/edge: 1

Window=4 Iteration=8
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 3      max edges/level: 4
mean edges/node:  1.000  mean count/edge: 1

Window=4 Iteration=9
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.200  mean count/edge: 1

Window=4 Iteration=10
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 3      max edges/level: 4
mean edges/node:  1.000  mean count/edge: 1

Starting phasing iterations

Window=4 Iteration=11
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.200  mean count/edge: 1

states/marker:    1.0

Window=4 Iteration=12
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.200  mean count/edge: 1

states/marker:    1.0

Window=4 Iteration=13
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.200  mean count/edge: 1

states/marker:    1.0

Window=4 Iteration=14
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.200  mean count/edge: 1

states/marker:    1.0

Window=4 Iteration=15
Time for building model:         0 seconds
Time for sampling (singles):     0 seconds
DAG statistics
mean edges/level: 2      max edges/level: 2
mean edges/node:  1.200  mean count/edge: 1

states/marker:    1.0

Number of markers:                  14
Total time for building model: 0 seconds
Total time for sampling:       0 seconds
Total run time:                0 seconds

End time: 01:05 PM IST on 04 May 2018
beagle.09Nov15.d2a.jar finished
/opt/installers/bamgineer/CEPH_CCP_test_data/CCP_SIMULATION040518_R1
 ___ phasing vcf file ___ 

VCFtools - v0.1.12a
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
	--vcf /opt/installers/bamgineer/CEPH_CCP_test_data/CCP_SIMULATION040518_R1/phasedvcfdir/hap1_het.vcf
	--thin 50
	--out /opt/installers/bamgineer/CEPH_CCP_test_data/CCP_SIMULATION040518_R1/phasedvcfdir/hap1_het_filtered
	--recode

After filtering, kept 0 out of 0 Individuals
Outputting VCF file...
After filtering, kept 5 out of a possible 5 Sites
Run Time = 0.00 seconds

VCFtools - v0.1.12a
(C) Adam Auton and Anthony Marcketta 2009

Parameters as interpreted:
	--vcf /opt/installers/bamgineer/CEPH_CCP_test_data/CCP_SIMULATION040518_R1/phasedvcfdir/hap2_het.vcf
	--thin 50
	--out /opt/installers/bamgineer/CEPH_CCP_test_data/CCP_SIMULATION040518_R1/phasedvcfdir/hap2_het_filtered
	--recode

After filtering, kept 0 out of 0 Individuals
Outputting VCF file...
After filtering, kept 7 out of a possible 7 Sites
Run Time = 0.00 seconds
